name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.2
  http: ^1.2.1
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  qr_flutter: ^4.1.0
  top_snackbar_flutter: ^3.1.0
  encrypt: ^5.0.3
  flutter_svg : ^2.0.1
  getwidget: ^4.0.0
  go_router: ^14.2.2                        
  shared_preferences: ^2.2.3
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.2
  sqflite: ^2.3.3
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.6
  pull_to_refresh_flutter3: ^2.0.2
  flutter_native_splash: ^2.4.1
  back_button_interceptor: ^7.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - properties.env
  - assets/images/
  - assets/images/logo/
  - assets/vectors/
  - assets/vectors/Bottombar/